stages:
  - publish
  - deliver

mirror:
  stage: publish
  script:
    - setsid ./ci/mirror.sh
  only:
    - /^(main.*)$/
  tags:
    - mirror

deliver:
  stage: deliver
  script:
    - setsid ./ci/docker-deliver.sh "bucket-backup" "2.1"
  only:
    refs:
      - /^(main.*)$/
  tags:
    - imagesbuilder
