version: "3.3"

services: 
  bucket-backup:
    image: comworkio/bucket-backup:1.0
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./test:/test
