version: "3.3"

services: 
  bucket-backup:
    image: comworkio/bucket-backup:1.0
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - MC_VERSION=RELEASE.2022-10-29T10-09-23Z
    env_file:
      - .env
    volumes:
      - ./test:/test
