version: "3.3"

services: 
  bucket-backup:
    image: comworkio/bucket-backup:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - MC_VERSION=RELEASE.2022-10-29T10-09-23Z
